### ISSUE TITLE
No support for PHP 5.3?

### ISSUE THREAD

**Issue by aapis** [monque/PHP-Migration#10]
I'm trying to determine if we can upgrade some of our servers that currently run 5.3, but this code requires at least 5.4 due to the array syntax.  Would you support merging a PR that changed the array syntax to support PHP 5.3?

Just for clarity, here's the error I get when running the .phar:
`PHP Parse error:  syntax error, unexpected '[' in phar:///home/star/phpmig.phar/src/App.php on line 83`

**Comment by monque** [comment]
Yes, I have done this on version [`0.2.0`](https://github.com/monque/PHP-Migration/releases/tag/v0.2.0)

_Changing the minimum supported version on PHP from 5.3 to 5.5_

Reasons:
- `trait`
- short array syntax
- [5.3 is not under supported](http://php.net/supported-versions.php).

As you are trying to upgrade PHP, why not get a new version of PHP?

**Comment by aapis** [comment]
I was hoping to use this tool to determine if I could upgrade to a new version of PHP.  I guess it won't work for me.  Thanks anyways!

**Comment by monque** [comment]
Sorry to hear that.

We are hardworking on a code analysis tool online, maybe it will solve your
problem.
