### ISSUE TITLE
nikic vendor dependency too restrictive

### ISSUE THREAD

**Issue by llaville** [monque/PHP-Migration#2]
Dependency is too restrictive, and does not allow benefit of new versions

```
 "nikic/php-parser": "~1.0.1",
```

You should changed this at least to 

```
 "nikic/php-parser": "~1.1",
```

Better will be `~1.3` or even `~1.2`

**Comment by monque** [comment]
commit 066c57b
using `^1.0.1` operator, equivalent to `>=1.0.1 <2.0.0`
