### ISSUE TITLE
Run not on Windows

### ISSUE THREAD

**Issue by c-key** [monque/PHP-Migration#5]
I have downloaded the phar and want to run it on a windows machine like this "php phpmig.phar <file>".
But always I get the error "Fatal error: Allowed memory size of 262144 bytes exhausted (tried to allocate 11
52 bytes) in phar://path/to/phpmig/phpmig_2015-10-15.phar/src/Ch
anges/AbstractRemoved.php on line 49".

I have tried to change the memory_limit to 1 gb than to 4 gb and the error is still there.

**Comment by monque** [comment]
> It seems that no `memory_limit` setting in the phar.
> 
> Maybe you could try `php -i | grep memory` to confirm your memory_limit.

Actually I set `memory_limit` in previous version, so you should try `0.1.2`.

`phar` has updated.

**Comment by c-key** [comment]
I want to test the issue but with the new phar from "http://wangyuchen.org/misc/phpmig.phar" I got always the message "No spot found".

My calls are:
- php phpmig_2015-10-21.phar E:\xyz\index.php
- php phpmig_2015-10-21.phar --set to56 E:\xyz\index.php
- php phpmig_2015-10-21.phar E:\xyz\

**Comment by monque** [comment]
Could you show me your `index.php` file ?

Here's my test:

``` php
<?php
substr(&$str);
```

Result

``` sh
monque@e4300 ~ $ php phpmig.phar a.php 

File: a.php
--------------------------------------------------------------------------------
Found 1 spot(s), 1 identified
--------------------------------------------------------------------------------
    3 | FATAL      | * | 5.4.0 | Call-time pass-by-reference has been removed
--------------------------------------------------------------------------------
```

**Comment by c-key** [comment]
I have tested another directory with a file that have a preg_replace and it worked. So sorry for my false test-directory. But the good news are, it runs on windows without any memory_limit. Thanks.
